name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Please update the test workflow cross-compile matrix when adding a new
        # target here.
        target: [
          aarch64-linux-android,
          arm-linux-androideabi,
          armv7-linux-androideabi,
          x86_64-unknown-linux-musl,
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - run: |
          cargo install --path=cli --root=. --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: blazecli-${{ matrix.target }}
          path: bin/blazecli
